In [1]:
round(123.235, 2)

123.23

In [2]:
round(123123.1221,-2)

123100.0

In [3]:
n = 123.1234235
r = f"{n:.3f}"

r

'123.123'

In [4]:
a = 3.12
b = 3.03
print(a+b)
print((a+b) == 6.15)

6.15
True


In [5]:
data = b'\x00\x124V\x00x\x90\xab\x00\xcd\xef\x01\x00#\x004'
print(data)

b'\x00\x124V\x00x\x90\xab\x00\xcd\xef\x01\x00#\x004'


In [6]:
int.from_bytes(data)


94522842520747284487117727783387188

In [7]:
a = float('-inf')

print(a+32)

-inf


In [8]:
from fractions import Fraction

a = Fraction(12,3)
b = Fraction(2,2)
print(Fraction(a+b))

5


In [9]:
import numpy as np
from numpy import float64

print(np.zeros(shape=(10,10), dtype=float64))

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [10]:
np.sin(np.random.randn(3,3))

array([[ 0.9631852 ,  0.54069107, -0.14216618],
       [ 0.94044015,  0.84466072, -0.74612995],
       [-0.99173937, -0.9744599 , -0.9784182 ]])

In [11]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)

a[:,1]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


array([ 2,  6, 10])

In [12]:
print(a[:,1])

[ 2  6 10]


In [13]:
print(a[0:2,:])

[[1 2 3 4]
 [5 6 7 8]]


In [14]:
np.where(a==1,1000,a)

array([[1000,    2,    3,    4],
       [   5,    6,    7,    8],
       [   9,   10,   11,   12]])

In [15]:
m = np.matrix([[ 1, -2, 3],
[ 0, 4, 5],
[ 7, 8, -9]])
m

matrix([[ 1, -2,  3],
        [ 0,  4,  5],
        [ 7,  8, -9]])

In [16]:
m.T # not inline, returns copy

matrix([[ 1,  0,  7],
        [-2,  4,  8],
        [ 3,  5, -9]])

In [17]:
v = np.matrix([[2],[3],[4]])

m*v 

matrix([[ 8],
        [32],
        [ 2]])

In [18]:
np.dot(m,v)
#matmul does the same thing

matrix([[ 8],
        [32],
        [ 2]])

In [19]:
np.multiply(m,v)

matrix([[  2,  -4,   6],
        [  0,  12,  15],
        [ 28,  32, -36]])

In [20]:
a = np.random.randint(0,10)
print(a)

1


In [21]:
np.random.random()

0.8320012482301898

In [22]:
from datetime import timedelta

In [23]:
a = timedelta(seconds = 12)
print(a)

0:00:12


In [24]:
from datetime import  datetime

In [25]:
a = datetime(2012, 9, 23)
a+timedelta(minutes = 21)

datetime.datetime(2012, 9, 23, 0, 21)

In [31]:
from dateutil.relativedelta import relativedelta
a + relativedelta(months=+1)
a + timedelta(minutes=+50, seconds=21)


datetime.datetime(2012, 9, 23, 0, 50, 21)

In [35]:
#printing days range:
from datetime import date

for i in range(1,5):
    print(date.today()+timedelta(days=i))

2025-12-22
2025-12-23
2025-12-24
2025-12-25


In [41]:
from datetime import datetime
text = '2012-09-20'

y = datetime.strptime(text, '%Y-%m-%d')
y

datetime.datetime(2012, 9, 20, 0, 0)

In [45]:
from pytz import datetime
from pytz import timezone

In [47]:
d = datetime(2012, 12, 21, 9, 30, 0)
central = timezone('A')
loc_d = central.localize(d)

TypeError: 'module' object is not callable. Did you mean: 'datetime.datetime(...)'?