In [14]:
import numpy as np

def sigmoid(x):
    """Implement sigmoid activation function."""
    return 1. / (1 + np.exp(-x))

def dense_layer(x, w, b):
    y = x@w + b
    return sigmoid(y)
# Simple demo
x = np.array([[1, 2], [3, 4]])
w = np.array([[0.5, 0.3], [0.2, 0.4]])
b = np.array([0.1, 0.2])

print("Input x:\n", x)
print("\nWeights w:\n", w)
print("\nBias b:\n", b)

result = dense_layer(x, w, b)
print("\nOutput:\n", result)

Input x:
 [[1 2]
 [3 4]]

Weights w:
 [[0.5 0.3]
 [0.2 0.4]]

Bias b:
 [0.1 0.2]

Output:
 [[0.73105858 0.78583498]
 [0.9168273  0.93702664]]


In [24]:
import pandas as pd
import random
import string

names = ["haseeb", "bilal", "hammad"]

df = pd.DataFrame({
    "id": [
        "".join(
            random.choice(names)
        ) for _ in range(100_000)
    ],
    "scores": [
        random.randint(1, 100) for _ in range(100_000)
    ],
})

df

id  scores
0      hammad      32
1      hammad      22
2      haseeb      25
3      haseeb      62
4      haseeb      11
...       ...     ...
99995  haseeb      55
99996  haseeb      66
99997  hammad      89
99998   bilal      12
99999   bilal      17

[100000 rows x 2 columns]