In [2]:
import pandas as pd
import numpy as np

df = pd.read_csv('retail_data.csv')
df.head()

Customer_ID  Age  Annual_Income      City Mixed_ID  Transaction_Date  \
0         1000   39            NaN  New York     ID_0        2023-01-01   
1         1001   33   87501.712418       NaN     10.0        2023-01-02   
2         1002   41            NaN  New York     ID_2  01-03-2023 04:00   
3         1003   50   80614.377811  New York     30.0        2023-01-04   
4         1004   32   42274.617116  New York     ID_4  01-05-2023 08:00   

   Spending_Score  
0             500  
1             600  
2            -150  
3             800  
4            1000

In [20]:
def gen_email(customer_id, domain="gmail.com"):
    return customer_id+'@'+domain
gen_email('123','gmail')

df.columns

df['email'] = df['Customer_ID'].apply(lambda x: gen_email(str(x), 'haseeb.com'))
df['email'].head()


0    1000@haseeb.com
1    1001@haseeb.com
2    1002@haseeb.com
3    1003@haseeb.com
4    1004@haseeb.com
Name: email, dtype: object

In [18]:
def greeter(name):
    return f"hello mr. {name}!!!\n"

print(df["Customer_ID"].iloc[:5].apply(lambda x: greeter(x)))

0    hello mr. 1000!!!\n
1    hello mr. 1001!!!\n
2    hello mr. 1002!!!\n
3    hello mr. 1003!!!\n
4    hello mr. 1004!!!\n
Name: Customer_ID, dtype: object


In [22]:
fav = np.full((2,2), 67)
fav

array([[67, 67],
       [67, 67]])

In [24]:
print("identity matrix: ", np.eye(fav.shape[0]))

identity matrix:  [[1. 0.]
 [0. 1.]]


In [25]:
int_ar = np.array([1,4,3,2], dtype=np.int32)
int_ar

array([1, 4, 3, 2], dtype=int32)

In [27]:
int_ar.size

4

In [29]:
int_ar.ndim

1

In [30]:
int_ar.nbytes

16

In [31]:
int_ar.itemsize

4

In [32]:
int_2d = np.array([ [1,2], [1,3], [1,4]])
int_2d

array([[1, 2],
       [1, 3],
       [1, 4]])

In [33]:
int_2d.ndim

2

In [35]:
print("elements: ", int_2d)

elements:  [[1 2]
 [1 3]
 [1 4]]


In [36]:
df.sample(3)

Customer_ID  Age  Annual_Income   City Mixed_ID  Transaction_Date  \
55          1055   44            NaN  Dubai    550.0        01/03/2023   
141         1141   48  132939.525727  Tokyo   1410.0        2023-06-02   
94          1094   31            NaN    NaN    ID_94  04-12-2023 20:00   

     Spending_Score            email  
55               26  1055@haseeb.com  
141              33  1141@haseeb.com  
94                1  1094@haseeb.com

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   Customer_ID       200 non-null    int64  
 1   Age               200 non-null    int64  
 2   Annual_Income     150 non-null    float64
 3   City              180 non-null    object 
 4   Mixed_ID          200 non-null    object 
 5   Transaction_Date  200 non-null    object 
 6   Spending_Score    200 non-null    int64  
 7   email             200 non-null    object 
dtypes: float64(1), int64(3), object(4)
memory usage: 12.6+ KB


In [38]:
df.describe(
)

Customer_ID         Age  Annual_Income  Spending_Score
count   200.000000  200.000000     150.000000      200.000000
mean   1099.500000   34.050000   66944.035593       64.900000
std      57.879185    9.343662   44112.004759      123.089215
min    1000.000000    8.000000   20544.840331     -150.000000
25%    1049.750000   27.000000   34622.941778       27.000000
50%    1099.500000   34.500000   57414.063223       47.000000
75%    1149.250000   39.250000   89210.836320       72.000000
max    1199.000000   62.000000  252850.244507     1000.000000

In [41]:
df['Age'].max()

np.int64(62)

In [42]:
max(df['Age'])

62

In [43]:
df.shape

(200, 8)

In [44]:
df.tail()

Customer_ID  Age  Annual_Income      City Mixed_ID  Transaction_Date  \
195         1195   38   26324.549797  New York   1950.0        2023-07-31   
196         1196   26   26251.311600     Tokyo   ID_196        2023-08-01   
197         1197   36            NaN     Dubai   1970.0        2023-08-02   
198         1198   35   88529.885880  New York   ID_198  08-03-2023 12:00   
199         1199   23   63777.688860    London   1990.0  08-04-2023 14:00   

     Spending_Score            email  
195               3  1195@haseeb.com  
196              32  1196@haseeb.com  
197              10  1197@haseeb.com  
198              74  1198@haseeb.com  
199              83  1199@haseeb.com